/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpenrouterCallbackRouteImport } from './routes/openrouter/callback'
import { Route as CChatIdRouteImport } from './routes/c/$chatId'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiTypingRouteImport } from './routes/api/typing'
import { Route as ApiOpenrouterKeyRouteImport } from './routes/api/openrouter-key'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as ApiWorkflowGenerateTitleRouteImport } from './routes/api/workflow/generate-title'
import { Route as ApiWorkflowExportChatRouteImport } from './routes/api/workflow/export-chat'
import { Route as ApiWorkflowDeleteAccountRouteImport } from './routes/api/workflow/delete-account'
import { Route as ApiWorkflowCleanupRouteImport } from './routes/api/workflow/cleanup'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenrouterCallbackRoute = OpenrouterCallbackRouteImport.update({
  id: '/openrouter/callback',
  path: '/openrouter/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CChatIdRoute = CChatIdRouteImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTypingRoute = ApiTypingRouteImport.update({
  id: '/api/typing',
  path: '/api/typing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenrouterKeyRoute = ApiOpenrouterKeyRouteImport.update({
  id: '/api/openrouter-key',
  path: '/api/openrouter-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowGenerateTitleRoute =
  ApiWorkflowGenerateTitleRouteImport.update({
    id: '/api/workflow/generate-title',
    path: '/api/workflow/generate-title',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowExportChatRoute = ApiWorkflowExportChatRouteImport.update({
  id: '/api/workflow/export-chat',
  path: '/api/workflow/export-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowDeleteAccountRoute =
  ApiWorkflowDeleteAccountRouteImport.update({
    id: '/api/workflow/delete-account',
    path: '/api/workflow/delete-account',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowCleanupRoute = ApiWorkflowCleanupRouteImport.update({
  id: '/api/workflow/cleanup',
  path: '/api/workflow/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/openrouter-key': typeof ApiOpenrouterKeyRoute
  '/api/typing': typeof ApiTypingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/c/$chatId': typeof CChatIdRoute
  '/openrouter/callback': typeof OpenrouterCallbackRoute
  '/api/workflow/cleanup': typeof ApiWorkflowCleanupRoute
  '/api/workflow/delete-account': typeof ApiWorkflowDeleteAccountRoute
  '/api/workflow/export-chat': typeof ApiWorkflowExportChatRoute
  '/api/workflow/generate-title': typeof ApiWorkflowGenerateTitleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/openrouter-key': typeof ApiOpenrouterKeyRoute
  '/api/typing': typeof ApiTypingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/c/$chatId': typeof CChatIdRoute
  '/openrouter/callback': typeof OpenrouterCallbackRoute
  '/api/workflow/cleanup': typeof ApiWorkflowCleanupRoute
  '/api/workflow/delete-account': typeof ApiWorkflowDeleteAccountRoute
  '/api/workflow/export-chat': typeof ApiWorkflowExportChatRoute
  '/api/workflow/generate-title': typeof ApiWorkflowGenerateTitleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/api/models': typeof ApiModelsRoute
  '/api/openrouter-key': typeof ApiOpenrouterKeyRoute
  '/api/typing': typeof ApiTypingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/c/$chatId': typeof CChatIdRoute
  '/openrouter/callback': typeof OpenrouterCallbackRoute
  '/api/workflow/cleanup': typeof ApiWorkflowCleanupRoute
  '/api/workflow/delete-account': typeof ApiWorkflowDeleteAccountRoute
  '/api/workflow/export-chat': typeof ApiWorkflowExportChatRoute
  '/api/workflow/generate-title': typeof ApiWorkflowGenerateTitleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/models'
    | '/api/openrouter-key'
    | '/api/typing'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/c/$chatId'
    | '/openrouter/callback'
    | '/api/workflow/cleanup'
    | '/api/workflow/delete-account'
    | '/api/workflow/export-chat'
    | '/api/workflow/generate-title'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/models'
    | '/api/openrouter-key'
    | '/api/typing'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/c/$chatId'
    | '/openrouter/callback'
    | '/api/workflow/cleanup'
    | '/api/workflow/delete-account'
    | '/api/workflow/export-chat'
    | '/api/workflow/generate-title'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/api/models'
    | '/api/openrouter-key'
    | '/api/typing'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/c/$chatId'
    | '/openrouter/callback'
    | '/api/workflow/cleanup'
    | '/api/workflow/delete-account'
    | '/api/workflow/export-chat'
    | '/api/workflow/generate-title'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiModelsRoute: typeof ApiModelsRoute
  ApiOpenrouterKeyRoute: typeof ApiOpenrouterKeyRoute
  ApiTypingRoute: typeof ApiTypingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  CChatIdRoute: typeof CChatIdRoute
  OpenrouterCallbackRoute: typeof OpenrouterCallbackRoute
  ApiWorkflowCleanupRoute: typeof ApiWorkflowCleanupRoute
  ApiWorkflowDeleteAccountRoute: typeof ApiWorkflowDeleteAccountRoute
  ApiWorkflowExportChatRoute: typeof ApiWorkflowExportChatRoute
  ApiWorkflowGenerateTitleRoute: typeof ApiWorkflowGenerateTitleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openrouter/callback': {
      id: '/openrouter/callback'
      path: '/openrouter/callback'
      fullPath: '/openrouter/callback'
      preLoaderRoute: typeof OpenrouterCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/typing': {
      id: '/api/typing'
      path: '/api/typing'
      fullPath: '/api/typing'
      preLoaderRoute: typeof ApiTypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openrouter-key': {
      id: '/api/openrouter-key'
      path: '/api/openrouter-key'
      fullPath: '/api/openrouter-key'
      preLoaderRoute: typeof ApiOpenrouterKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow/generate-title': {
      id: '/api/workflow/generate-title'
      path: '/api/workflow/generate-title'
      fullPath: '/api/workflow/generate-title'
      preLoaderRoute: typeof ApiWorkflowGenerateTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow/export-chat': {
      id: '/api/workflow/export-chat'
      path: '/api/workflow/export-chat'
      fullPath: '/api/workflow/export-chat'
      preLoaderRoute: typeof ApiWorkflowExportChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow/delete-account': {
      id: '/api/workflow/delete-account'
      path: '/api/workflow/delete-account'
      fullPath: '/api/workflow/delete-account'
      preLoaderRoute: typeof ApiWorkflowDeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow/cleanup': {
      id: '/api/workflow/cleanup'
      path: '/api/workflow/cleanup'
      fullPath: '/api/workflow/cleanup'
      preLoaderRoute: typeof ApiWorkflowCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiModelsRoute: ApiModelsRoute,
  ApiOpenrouterKeyRoute: ApiOpenrouterKeyRoute,
  ApiTypingRoute: ApiTypingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  CChatIdRoute: CChatIdRoute,
  OpenrouterCallbackRoute: OpenrouterCallbackRoute,
  ApiWorkflowCleanupRoute: ApiWorkflowCleanupRoute,
  ApiWorkflowDeleteAccountRoute: ApiWorkflowDeleteAccountRoute,
  ApiWorkflowExportChatRoute: ApiWorkflowExportChatRoute,
  ApiWorkflowGenerateTitleRoute: ApiWorkflowGenerateTitleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
